In [5]:
#SHUFFLE
import numpy as np

var = np.array([1,2,3,4,5,6])

np.random.shuffle(var)

print(var)


[2 6 4 3 5 1]


In [9]:
#UNIQUE: to get the unique data not the repeated ones

var1 = np.array([1,2,2,4,5,4,5,3,3,3,6,2,8,8,5,5,3])

x = np.unique(var1)

print(x)

#to get the INDEX too

y = np.unique(var1,return_index = True)

print()
print(y)

#to get the FREQUNCY too

z = np.unique(var1,return_index = True, return_counts = True)

print()
print(z)




[1 2 3 4 5 6 8]

(array([1, 2, 3, 4, 5, 6, 8]), array([ 0,  1,  7,  3,  4, 10, 12]))

(array([1, 2, 3, 4, 5, 6, 8]), array([ 0,  1,  7,  3,  4, 10, 12]), array([1, 3, 4, 2, 4, 1, 2]))


In [14]:
#FLATTEN & RAVEL, MULTI DIMEN TO ONE DIMEN

var2 = np.array([[[12,4,53,4],[3,5,7,8],[2,6,8,4]]])

print(var2)
print()

print("Flatten: ", var2.flatten()) #flatt copy the arrray
print()

print("Flatten: F", var2.flatten(order = "F"))
print()

print("Flatten: C", var2.flatten(order = "C"))
print()


print("Ravel :", var2.ravel()) #ravel view the array





[[[12  4 53  4]
  [ 3  5  7  8]
  [ 2  6  8  4]]]

Flatten:  [12  4 53  4  3  5  7  8  2  6  8  4]

Flatten: F [12  3  2  4  5  6 53  7  8  4  8  4]

Flatten: C [12  4 53  4  3  5  7  8  2  6  8  4]

Ravel : [12  4 53  4  3  5  7  8  2  6  8  4]
