In [ ]:
import numpy as np

#Addition 1D

var = np.array([1,2,3,4])

varAdd = var + 3

print(varAdd)



[4 5 6 7]


In [2]:
#using functions

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

add = np.add(arr1, arr2)

print(add)

[ 6  8 10 12]


In [ ]:
#in 2D array add

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[1,2,3], [4,5,6]])

add  = np.add(arr1, arr2)

print(add)

[[ 2  4  6]
 [ 8 10 12]]


In [2]:
#in 2D array multi
import numpy as np

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[1,2,3], [4,5,6]])

print(arr1)
print()
print(arr2)
print()



multi  = np.multiply(arr1, arr2) #each index is multiplied with each

print(multi)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [11]:
#ARTHMETIC FUNCTIONS
arr1 = np.array([1,2,5,8,5,3,6,2,1,7,8,0])

print("min :",np.min(arr1))
print("max :",np.max(arr1))

#position

print("pos of min :",np.argmin(arr1))
print("pos of max :",np.argmax(arr1))

#sqrt(of individual element)

print("sqrt: ", np.sqrt(arr1))



min : 0
max : 8
pos of min : 11
pos of max : 3
sqrt:  [1.         1.41421356 2.23606798 2.82842712 2.23606798 1.73205081
 2.44948974 1.41421356 1.         2.64575131 2.82842712 0.        ]


In [ ]:
#in 2D

var = np.array([[1,5,8,4] , [2,6,3,8]])

print(np.min(var, axis = 0))



[1 5 3 4]


In [ ]:
#cumsum (cumulutive sum, addding previous terms of the result)

arr1 = np.array([1,2,5,8,5,3,6,2,1,7,8,0])

print("cumsum :", np.cumsum(arr1))

cumsum : [ 1  3  8 16 21 24 30 32 33 40 48 48]
