In [5]:
#SEARCH ARRAY

import numpy as np

var = np.array([1,2,65,7,8,8,9,4])

x = np.where( var == 2) #will give the index of that element 
y = np.where( var == 8)
z = np.where( (var*2) == 4) #which element when multiplied by 2 will give 4
m = np.where((var%2) == 0)

print(x)
print(y)
print(z)
print(m)



(array([1]),)
(array([4, 5]),)
(array([1]),)
(array([1, 4, 5, 7]),)


In [12]:
#Search Sorted Array

var1 = np.array([2,5,7,9,12,17,45]) #array should be sorted

x1 = np.searchsorted( var1, 15) #i.e., 15 can be placed at index no.5

x2 = np.searchsorted(x1, [8,9,13,15], side = "right") #getting error to this

print(x1)
print()
print(x2)


ValueError: object of too small depth for desired array

In [15]:
#SORT ARRAY

var2 = np.array([1,2,65,7,8,8,9,4])

var3 = np.array([[1,6,2],[15,2,3]])

sort = np.sort(var2)
sort2 = np.sort(var3)

print(sort)
print()
print(sort2)


[ 1  2  4  7  8  8  9 65]

[[ 1  2  6]
 [ 2  3 15]]


In [19]:
#FILTER ARRAY: getting some elements out of an existing array and creating a new array out of them

var4 = np.array([1,5,7,18,65,48])

filt = [True,False,False,True,True,True]
filt2 = [True,False,True,True,True,False]

new_a = var4[filt]
new_b = var4[filt2]

print(new_a)
print()
print(new_b)

#nice!!!!!!!!!!!!!!


[ 1 18 65 48]

[ 1  7 18 65]
