In [2]:
#INDEXING

import numpy as np

x = np.array([3,4,5,6])

#print index element

print(x[2])



5


In [4]:
#in 2D array

y = np.array([[1,2,3],[4,5,6]])

print(y)
print()
print(y[0,2])

print(y[1,1])

[[1 2 3]
 [4 5 6]]

3
5


In [7]:
#in 3D array

z = np.array([[[1,2],[3,4]]])

print(z)
print()
print(z[0,1,1])




[[[1 2]
  [3 4]]]

4


In [6]:
#SLICING
import numpy as np
#1D
arr = np.array([1,2,3,4,5])
print(arr)
print()

#to pull out a particular set of element, like 2,3,4 or 3,4,5
print("2 to 5 : ",arr[1:5] )
print("1 to 3 : ",arr[0:3] )
print("2 to end : ",arr[1:] )
print("start to 4 : ",arr[:4] )

#jumping elemnts(start:stop:jump/common diff of index)

print("stop : ",arr[::2])
print("stop : ",arr[3::2])

[1 2 3 4 5]

2 to 5 :  [2 3 4 5]
1 to 3 :  [1 2 3]
2 to end :  [2 3 4 5]
start to 4 :  [1 2 3 4]
stop :  [1 3 5]
stop :  [4]


In [18]:
#in 2D
import numpy as np
arr2 = np.array([[4,5,6,5,8,9],[7,4,2,4,5,6],[4,8,9,7,4,2]])
print(arr2)
print()

print(arr2[0,2:5])
print(arr2[0,0:5:2])
print(arr2[2,0:6:3])
print(arr2[2,2::2])



[[4 5 6 5 8 9]
 [7 4 2 4 5 6]
 [4 8 9 7 4 2]]

[6 5 8]
[4 6 8]
[4 7]
[9 4]
