In [3]:
#INSERT
import numpy as np

var = np.array([1,2,4,5])

print(var)

new_var = np.insert(var, 2, 40) #can be also done Append function


#at multiple index
new_var2 = np.insert(var, (2,4), 40) #{array, index, value(only int is accaeptd)}

print(new_var)
print()
print(new_var2)






[1 2 4 5]
[ 1  2 40  4  5]

[ 1  2 40  4  5 40]


In [12]:
#in 2D

var1 = np.array([[1,2,3],[4,6,6],[7,6,7]])

print(var1)
print()

v1 = np.insert(var1, 2, 16, axis = 1)
v2 = np.insert(var1, 2, 16, axis = 0)
v3 = np.insert(var1, 2, [16,23,56], axis = 1) #new column
v4 = np.insert(var1, 2, [16,23,56], axis = 0) #new row

print(v1)
print()
print(v2)
print()
print(v1)
print()
print(v3)
print()
print(v4)



[[1 2 3]
 [4 6 6]
 [7 6 7]]

[[ 1  2 16  3]
 [ 4  6 16  6]
 [ 7  6 16  7]]

[[ 1  2  3]
 [ 4  6  6]
 [16 16 16]
 [ 7  6  7]]

[[ 1  2 16  3]
 [ 4  6 16  6]
 [ 7  6 16  7]]

[[ 1  2 16  3]
 [ 4  6 23  6]
 [ 7  6 56  7]]

[[ 1  2  3]
 [ 4  6  6]
 [16 23 56]
 [ 7  6  7]]


In [13]:
#DELET

import numpy as np

var5 = np.array([1,2,4,5])

print(var)

d = np.delete(var5, 2)

print(d)


[1 2 4 5]
[1 2 5]


In [15]:
var1 = np.array([[1,2,3],[4,6,6],[7,6,7]])

print(var1)
print()

d1 = np.delete(var1, 1, axis = 1) #obiviously one element can't be deleted 

print(d1)




[[1 2 3]
 [4 6 6]
 [7 6 7]]

[[1 3]
 [4 6]
 [7 7]]
