In [4]:
#ITERATING

import numpy as np

arr = np.array([1,2,3,4,5])

for  i in arr:
    print(i)

1
2
3
4
5


In [6]:
#in 2D

arr2 = np.array([[1,3,4],[6,4,3]])

#rowwise iteration
for j in arr2:
    print(j)

#elemntwise
for k in arr2:
    for l in k:
        print(l)




[1 3 4]
[6 4 3]
1
3
4
6
4
3


In [7]:
#in 3D

arr3 = np.array([[[1,3,4],[6,4,3],[6,7,8]]])

#rowwise iteration
for j in arr3:
    print(j)

#elemntwise
for k in arr3:
    for l in k:
        for m in l:
            print(m)



[[1 3 4]
 [6 4 3]
 [6 7 8]]
1
3
4
6
4
3
6
7
8


In [10]:
#USING FUNCTIONS{nditer()}

#in 2D

arr2 = np.array([[1,3,4],[6,4,3]])


for i in np.nditer(arr2):
    print(i)

print()

#in 3D

arr3 = np.array([[[1,3,4],[6,4,3],[6,7,8]]])

for j in np.nditer(arr3):
    print(j)



1
3
4
6
4
3

1
3
4
6
4
3
6
7
8


In [11]:
#USING FUNCTIONS to get the indexing + datatype of elements too {ndenumerate()}

#in 2D

arr2 = np.array([[1,3,4],[6,4,3]])


for i in np.ndenumerate(arr2):
    print(i)

print()

#in 3D

arr3 = np.array([[[1,3,4],[6,4,3],[6,7,8]]])

for j in np.ndenumerate(arr3):
    print(j)



((0, 0), np.int64(1))
((0, 1), np.int64(3))
((0, 2), np.int64(4))
((1, 0), np.int64(6))
((1, 1), np.int64(4))
((1, 2), np.int64(3))

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(3))
((0, 0, 2), np.int64(4))
((0, 1, 0), np.int64(6))
((0, 1, 1), np.int64(4))
((0, 1, 2), np.int64(3))
((0, 2, 0), np.int64(6))
((0, 2, 1), np.int64(7))
((0, 2, 2), np.int64(8))
