In [2]:
#JOIN ARRAY

import numpy as np

var = np.array([1,2,3,4,5])

var1 = np.array([3,5,7,8,5])

join = np.concatenate((var, var1))

print(join)


[1 2 3 4 5 3 5 7 8 5]


In [5]:
#in 2D
var = np.array([[1,2,3],[5,8,9]])

var1 = np.array([[3,5,7],[4,6,7]])

print(var)
print()
print(var1)
print()

join = np.concatenate((var, var1), axis = 1)

print(join)
print()
join1 = np.concatenate((var, var1), axis = 0)
print(join1)




[[1 2 3]
 [5 8 9]]

[[3 5 7]
 [4 6 7]]

[[1 2 3 3 5 7]
 [5 8 9 4 6 7]]

[[1 2 3]
 [5 8 9]
 [3 5 7]
 [4 6 7]]


In [6]:
#STACK FUNCTION

var = np.array([1,2,3,4,5])

var1 = np.array([3,5,7,8,5])

join = np.stack((var, var1), axis = 0)
join1 = np.hstack((var, var1)) #row
join2 = np.vstack((var, var1)) #column
join3 = np.dstack((var, var1)) #height

print(join)
print()
print(join1)
print()
print(join2)
print()
print(join3)
print()


[[1 2 3 4 5]
 [3 5 7 8 5]]

[1 2 3 4 5 3 5 7 8 5]

[[1 2 3 4 5]
 [3 5 7 8 5]]

[[[1 3]
  [2 5]
  [3 7]
  [4 8]
  [5 5]]]



In [4]:
#SPLITT ARRAY

import numpy as np
#1D

arr = np.array([1,2,3,4,5])

split = np.array_split(arr, 3)

print(split)

print(split[1]) #index of ssplitted array
 

[array([1, 2]), array([3, 4]), array([5])]
[3 4]


In [7]:
#in 2D

arr2 = np.array([[1,2],[3,4],[5,6]])

split1 = np.array_split(arr2, 3)
split2 = np.array_split(arr2, 3, axis = 1)

print(split1)
print()
print(split2)

#for j in np.ndenumerate(split2):
 #   print(j)


[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]
