In [2]:
#MATRIX

#yes!!! matrix and array multiplications are different

#creating a matrix

import numpy as np

mat = np.matrix([[1,2,3],[5,6,7]])

print(mat)
print(type(mat))

[[1 2 3]
 [5 6 7]]
<class 'numpy.matrix'>


In [5]:
#multiplication

arr1 = np.matrix([[1,2],[4,5]])
arr2 = np.matrix([[1,5],[2,5]]) #it has to be square matrix

print(arr2*arr1)


[[21 27]
 [22 29]]


In [11]:
#matrix functions

#TRANSPOSE / Swapaxes
arr3 = np.matrix([[1,2,3],[4,5,3],[3,4,5]])
print(arr3)
print()

trans = np.transpose(arr3) #Swapaxes works in the same way 

#OR

trans1 = arr3.T

print(trans)
print()
print(trans1)
print()

#swapaxes

print("Swap : ",np.swapaxes(arr3,0,1))



[[1 2 3]
 [4 5 3]
 [3 4 5]]

[[1 4 3]
 [2 5 4]
 [3 3 5]]

[[1 4 3]
 [2 5 4]
 [3 3 5]]

Swap :  [[1 4 3]
 [2 5 4]
 [3 3 5]]


In [12]:
#INVERSE
arr1 = np.matrix([[1,2],[4,5]])

inve = np.linalg.inv(arr1)

print(inve) 


[[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]


In [14]:
#POWER

arr1 = np.matrix([[1,2],[4,5]])

power_n = np.linalg.matrix_power(arr1, 2) # 2 = power

power_0 = np.linalg.matrix_power(arr1, 0) # identity matrix

print(power_n)
print()
print(power_0)



[[ 9 12]
 [24 33]]

[[1 0]
 [0 1]]


In [15]:
#DETERMINANAT

arr1 = np.matrix([[1,2],[4,5]])

deter = np.linalg.det(arr1)

print(deter)

-2.9999999999999996
