In [1]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
vat = np.array([1,2,3,4])

print(vat)


[1 2 3 4]


In [2]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

add = np.add(arr1, arr2)
print(add)

[5 7 9]
