In [ ]:
import numpy as np

#SHAPE

var  = np.array([[1,4], [3,7]])

print(var)
print()
print(var.shape) # 2 cross 2


[[1 4]
 [3 7]]

(2, 2)


In [ ]:
var1 = np.array([1,2,3,4], ndmin = 4) #to make it n dimentional

print(var1)
print(var1.ndim)
print()
print(var1.shape) #kaise bana???



[[[[1 2 3 4]]]]
4

(1, 1, 1, 4)


In [5]:
#Reshape

import numpy as np

var2 = np.array([1,2,3,4,5,6])

x = var2.reshape(3,2) #3 = no.of rows, 2 = no. of elements
y = var2.reshape(2,3)
print(x)
print()
print(y)
print()
print(x.ndim)
print()
print(y.ndim)




[[1 2]
 [3 4]
 [5 6]]

[[1 2 3]
 [4 5 6]]

2

2


In [13]:
#BROADCASTING
import numpy as np

var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3])

#var3 = np.add(var1, var2)

print(var1+var2)



ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [17]:
#no broadcast error if the number of rows matched with dusre ke rows,
import numpy as np

x = np.array([[1],[2]]) 
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

add = np.add(x,y)

print(add)



(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


In [20]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([10, 20, 30])
print(array1)
print()
print(array2)
print()
result = array1 + array2
print(result)


[[1 2 3]
 [4 5 6]]

[10 20 30]

[[11 22 33]
 [14 25 36]]


In [21]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[10], [20]])

result = array1 + array2
print(result)



[[11 12 13]
 [24 25 26]]
